export const dataProducts = [
  {
    id: 1,
    title: "Luxury Electric Sedan",
    name: "Tesla Model S",
    image:
      "https://www.tesla.com/sites/default/files/modelsx-new/social/model-s-hero-social.jpg",
    model: "Model S",
    year: 2023,
    company: "Tesla",
    price: "$89,990",
    inCart: false,
    count: 1,
  },
  {
    id: 2,
    title: "Iconic American Muscle",
    name: "Ford Mustang",
    image:
      "https://www.ford.com/is/image/content/dam/brand_ford/en_us/brand/cars/mustang/2023/MY23-Mustang-Features_2-3_4.jpg",
    model: "Mustang GT",
    year: 2024,
    company: "Ford",
    price: "$55,300",
    inCart: false,
    count: 1,
  },
  {
    id: 3,
    title: "Compact Executive Sedan",
    name: "BMW 3 Series",
    image:
      "https://www.bmwusa.com/content/dam/bmwusa/3-series/sedan/2023/navigation/BMW-MY23-G20-3Series-Overview-Navigation.png",
    model: "330i",
    year: 2023,
    company: "BMW",
    price: "$43,800",
    inCart: false,
    count: 1,
  },
  {
    id: 4,
    title: "Luxury Mid-Size Sedan",
    name: "Audi A6",
    image:
      "https://www.audiusa.com/content/dam/nemo/us/models/a6/my-2023/navigation/A6_MY23_001_NAVIGATION_1920x1080_1.jpg",
    model: "A6 Quattro",
    year: 2024,
    company: "Audi",
    price: "$58,900",
    inCart: false,
    count: 1,
  },
  {
    id: 5,
    title: "Premium Compact Sedan",
    name: "Mercedes-Benz C-Class",
    image:
      "https://www.mbusa.com/content/dam/mb-nafta/us/myco/my24/c/sedan/class-page/2024-C-Sedan-Class-Page-Hero-XL.jpg",
    model: "C300",
    year: 2024,
    company: "Mercedes-Benz",
    price: "$45,850",
    inCart: false,
    count: 1,
  },
  {
    id: 6,
    title: "High-Performance SUV",
    name: "Porsche Cayenne",
    image:
      "https://files.porsche.com/filestore/image/multimedia/none/970x647/rd-2019-cayenne-modelimage-sideshot/normal/e3e62ed1-7586-11ea-80c9-005056bbdc38;sJ;twebp/porsche-normal.webp",
    model: "Cayenne S",
    year: 2023,
    company: "Porsche",
    price: "$86,500",
    inCart: false,
    count: 1,
  },
  {
    id: 7,
    title: "Affordable Electric Crossover",
    name: "Hyundai Kona Electric",
    image:
      "https://www.hyundaiusa.com/us/en/images/vehicles/kona-electric/2023/gallery/exterior_1920x1080.jpg",
    model: "Kona Electric",
    year: 2023,
    company: "Hyundai",
    price: "$34,000",
    inCart: false,
    count: 1,
  },
  {
    id: 8,
    title: "Luxury Full-Size SUV",
    name: "Range Rover",
    image:
      "https://media.landrover.com/sites/default/files/2023-01/2-Range-Rover-L405-1.jpg",
    model: "Range Rover Autobiography",
    year: 2024,
    company: "Land Rover",
    price: "$115,000",
    inCart: false,
    count: 1,
  },
  {
    id: 9,
    title: "All-Electric Sports Car",
    name: "Porsche Taycan",
    image:
      "https://files.porsche.com/filestore/image/multimedia/none/rd-2023-03-04-taycan-4s-modelimage/normal/c4d1524b-0764-11eb-80c9-005056bbdc38;sJ;twebp/porsche-normal.webp",
    model: "Taycan 4S",
    year: 2023,
    company: "Porsche",
    price: "$106,500",
    inCart: false,
    count: 1,
  },
  {
    id: 10,
    title: "Japanese Luxury Sedan",
    name: "Lexus ES",
    image:
      "https://www.lexus.com/cm-img/seo/es2024/landing/2024-Lexus-ES-Sedan-Overview-Hero-1200x800.jpg",
    model: "ES 350",
    year: 2024,
    company: "Lexus",
    price: "$43,000",
    inCart: false,
    count: 1,
  },
  {
    id: 11,
    title: "Electric Compact Hatchback",
    name: "Chevrolet Bolt EV",
    image:
      "https://www.chevrolet.com/content/dam/chevrolet/na/us/english/index/vehicles/2023/electric/bolt-ev/bmw/kbb-rh/02-images/2023-chevrolet-bolt-ev-masthead-03.jpg?imwidth=1200",
    model: "Bolt EV",
    year: 2023,
    company: "Chevrolet",
    price: "$27,000",
    inCart: false,
    count: 1,
  },
  {
    id: 12,
    title: "American Full-Size Pickup",
    name: "Ford F-150",
    image:
      "https://www.ford.com/cmslibs/content/dam/brand_ford/en_us/brand/resources/general/new-vehicles/2023/f150/rwd/23_FRD_F15_40222_GCBH_32.jpg",
    model: "F-150 Lariat",
    year: 2024,
    company: "Ford",
    price: "$58,000",
    inCart: false,
    count: 1,
  },
  {
    id: 13,
    title: "Sporty Compact Sedan",
    name: "Honda Civic",
    image:
      "https://automobiles.honda.com/-/media/Honda-Automobiles/Vehicles/2023/Civic-Sedan/2023-Honda-Civic-Sedan-LX-Front.jpg",
    model: "Civic Sport",
    year: 2023,
    company: "Honda",
    price: "$26,000",
    inCart: false,
    count: 1,
  },
  {
    id: 14,
    title: "Compact Crossover SUV",
    name: "Mazda CX-5",
    image:
      "https://www.mazdausa.com/siteassets/vehicles/2023/cx-5/cx5-2023_gallery_ext_side2.jpg",
    model: "CX-5 Grand Touring",
    year: 2023,
    company: "Mazda",
    price: "$32,000",
    inCart: false,
    count: 1,
  },
  {
    id: 15,
    title: "Luxury Sports Sedan",
    name: "Jaguar XF",
    image:
      "https://www.jaguarusa.com/images/2023-xf-hero-exterior-720x462-1.jpg",
    model: "XF R-Dynamic",
    year: 2024,
    company: "Jaguar",
    price: "$53,000",
    inCart: false,
    count: 1,
  },
  {
    id: 16,
    title: "High-End Electric SUV",
    name: "Tesla Model X",
    image:
      "https://www.tesla.com/sites/default/files/modelsx-new/social/model-x-hero-social.jpg",
    model: "Model X",
    year: 2023,
    company: "Tesla",
    price: "$109,990",
    inCart: false,
    count: 1,
  },
  {
    id: 17,
    title: "All-Terrain Luxury SUV",
    name: "Jeep Grand Cherokee",
    image:
      "https://www.jeep.com/content/dam/fca-brands/na/jeep/en_us/2023/grand-cherokee/l/reviews/images/2023-jeep-grand-cherokee-l-hero.png",
    model: "Grand Cherokee L",
    year: 2023,
    company: "Jeep",
    price: "$61,000",
    inCart: false,
    count: 1,
  },
  {
    id: 18,
    title: "Electric Compact SUV",
    name: "Nissan Ariya",
    image:
      "https://www.nissanusa.com/content/dam/Nissan/us/vehicles/ariya/2023/overview/2023-Nissan-Ariya-Highlights-1920x1080.jpg",
    model: "Ariya Platinum+",
    year: 2024,
    company: "Nissan",
    price: "$60,000",
    inCart: false,
    count: 1,
  },
  {
    id: 19,
    title: "Luxury Executive Sedan",
    name: "BMW 7 Series",
    image:
      "https://th.bing.com/th/id/OIP.tXBjJz6gfy5DLmv0IHK0ewHaE7?w=275&h=183&c=7&r=0&o=5&dpr=1.5&pid=1.7",
    model: "750i",
    year: 2024,
    company: "BMW",
    price: "$110,000",
    inCart: false,
    count: 1,
  },
  {
    id: 20,
    title: "Affordable Hybrid Sedan",
    name: "Toyota Camry Hybrid",
    image:
      "https://www.toyota.com/content/vehicle-landing/2023/camry-gallery/EX-2023-Toyota-Camry-Hybrid-SE-Nightshade-002.jpg",
    model: "Camry Hybrid SE",
    year: 2023,
    company: "Toyota",
    price: "$29,000",
    inCart: false,
    count: 1,
  },
];
// src/appData.jsx

export const prodInDetails = [
  {
    id: 1,
    title: "Compact City Car",
    name: "Honda Civic",
    image: "https://example.com/images/honda-civic.jpg",
    model: "EX",
    year: 2023,
    company: "Honda",
    price: "$25,000",
    inCart: false,
    count: 1,
    info: "a very good pained ass car",
  },
];
